---
all:
  children:
    # LOCAL
    local:
      hosts:
        local0:
          ansible_connection: local
          cluster_name: kubernetes
    # CLUSTER NODES
    allnodes:
      children:
        # MASTER NODES
        masters:
          children:
            # MASTER 1
            mainMaster:
              hosts:
                master0:
                  ansible_host: 172.26.22.120
                  name: 172.26.22.120
                  initial_advertise_peer_url: https://172.26.22.120:2380
                  listen_peer_url: https://172.26.22.120:2380
                  listen_client_urls:
                    - https://172.26.22.120:2379
                    - http://127.0.0.1:2379
                  advertise_client_url: https://172.26.22.120:2379
            # SECONDARY MASTERS
            secondaryMasters:
              hosts:
                master1:
                  ansible_host: 172.26.22.121
                  name: 172.26.22.121
                  initial_advertise_peer_url: https://172.26.22.121:2380
                  listen_peer_url: https://172.26.22.121:2380
                  listen_client_urls:
                    - https://172.26.22.121:2379
                    - http://127.0.0.1:2379
                  advertise_client_url: https://172.26.22.121:2379
                master2:
                  ansible_host: 172.26.22.122
                  name: 172.26.22.122
                  initial_advertise_peer_url: https://172.26.22.122:2380
                  listen_peer_url: https://172.26.22.122:2380
                  listen_client_urls:
                    - https://172.26.22.122:2379
                    - http://127.0.0.1:2379
                  advertise_client_url: https://172.26.22.122:2379
          # VARIABLES FOR MASTER NODES
          vars:
            pod_subnet: "100.96.0.0/11"
            apiserver_count: "3"
            cloudconfig_user: "dhna\\srvk8admin"
            cloudconfig_password: "icontrolkubernetes"
            cloudconfig_port: "443"
            cloudconfig_insecureflag: "1"
            cloudconfig_datacenters: "CH2"
            cloudconfig_server1: "dcpusvc01.dhna.corp"
            cloudconfig_datacenter1: "CH2"
            cloudconfig_defaultdatastore1: "CH2_VSAN_Cluster_01_vDS"
            cloudconfig_resourcepoolpath1: "/CH2/vm/K8"
            cloudconfig_folder: "K8"
            cloudconfig_scsicontrollertype: pvscsi
            cloudconfig_publicnetwork1: "dvP_CH2_C01_VLAN227"
            cloudconfig_server2: "dcpusvc02.dhna.corp"
            cloudconfig_datacenter2: "CH3"
            cloudconfig_defaultdatastore2: "CH3_VSAN_Cluster_01_vDS"
            cloudconfig_resourcepoolpath2: "CH3/CH3_VSAN_Cluster_01/resources"
            cloudconfig_publicnetwork2: "dvP_CH3_C01_VLAN227"
        # WORKER NODES
        workers:
          hosts:
            worker0:
              ansible_host: 172.26.22.251
              name: vgtk8worker01
            worker1:
              ansible_host: 172.26.22.128
              name: vgtk8worker02
            worker2:
              ansible_host: 172.26.22.57
              name: vgtk8worker03
      # VARIABLES FOR ALL NODES
      vars:
        master0_url: 172.26.22.120
        master1_url: 172.26.22.121
        master2_url: 172.26.22.122
        #Ingress Port Forwarding (ingress_http_node_port -> ingress_http_port)
        ingress0_url: 172.26.22.251
        ingress1_url: 172.26.22.128
        ingress2_url: 172.26.22.57
        ingress_http_port: 30080
        ingress_https_port: 30443
        ingress_http_node_port: 80
        ingress_https_node_port: 443
        master_api_port: 6443
        ansible_connection: ssh
        govc_url: dcpusvc01.dhna.corp
        govc_user: dhna\srvk8admin
        govc_pass: icontrolkubernetes
  # VARIABLES FOR ALL HOSTS
  vars:
    hostnames_api:
      - "- 172.26.22.120"
      - "- 172.26.22.121"
      - "- 172.26.22.122"
      - "- 172.26.22.123"
      - "- 172.26.22.124"
      - "- 172.26.22.125"
      - "- 172.26.22.126"
      - "- 172.26.22.127"
      - "- 172.26.22.128"
      - "- 10.96.0.1"
      - "- 127.0.0.1"
      - "- kubernetes"
      - "- kubernetes.default"
      - "- kubernetes.default.svc"
      - "- kubernetes.default.svc.cluster"
      - "- kubernetes.default.svc.cluster.local"
    hostnames:
      - 172.26.22.120
      - 172.26.22.121
      - 172.26.22.122
      - 172.26.22.123
      - 172.26.22.124
      - 172.26.22.125
      - 172.26.22.126
      - 172.26.22.127
      - 172.26.22.128
      - 10.96.0.1
      - 127.0.0.1
      - kubernetes
      - kubernetes.default
      - kubernetes.default.svc
      - kubernetes.default.svc.cluster
      - kubernetes.default.svc.cluster.local
    kubernetes_version: 1.12.3
    control_plane_endpoint: "127.0.0.1:32443"
